behaviors:
  FlappyBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 50000
      learning_rate: 0.003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 50000
    max_steps: 500000
    time_horizon: 128
    summary_freq: 50000
    threaded: false
