behaviors:
  FlappyBird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 5000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.15
      lambd: 0.94
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 20
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.85
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 100000
    time_horizon: 128
    summary_freq: 1000
    threaded: false
